### ISSUE TITLE
2023.3 --> Signature for MQTT msg_callback 'custom_components.spha.light.message_received' is not supported

### ISSUE THREAD

**Issue by sillevl** [sillevl/spha-home-assistant-component#1]
```
Logger: homeassistant.components.light
Source: components/mqtt/client.py:180
Integration: Light (documentation, issues)
First occurred: 19:35:22 (32 occurrences)
Last logged: 19:35:22

Error while setting up spha platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spha/light.py", line 40, in setup_platform
    add_entities([SphaLight(config, hass.components.mqtt, hass)])
  File "/config/custom_components/spha/light.py", line 73, in __init__
    self._mqtt.subscribe(self._state_topic, message_received)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 212, in subscribe
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 180, in async_subscribe
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Signature for MQTT msg_callback 'custom_components.spha.light.message_received' is not supported

```

**Comment by sillevl** [comment]
https://github.com/home-assistant/core/pull/88543

https://github.com/home-assistant/core/pull/88543/commits/aa8daf161beaee9e929d4dcc3b8a42561097e544

**Comment by sillevl** [comment]
https://developers.home-assistant.io/blog/2023/02/21/deprecated-callback-removed
